### ISSUE TITLE
ViewField Class not found

### ISSUE THREAD

**Issue by rs-dhansen** [vgrem/phpSPO#119] opened 2018-08-09 10:45 UTC
Hi,
when i try to look into view items i receive:

$views = $list->getViews()->getByTitle('MyBigView')->getViewFields();
$this->ctx->load($views);
$this->ctx->executeQuery();

Fatal error: Class 'Office365\PHP\Client\SharePoint\ViewField' not found in /php-spo/src/Runtime/ClientObjectCollection.php on line 245

What can i do?

My problem why i need views is large lists ( near 10000 rows)

**Comment by vgrem** [comment] 2019-10-21 22:56
I propose to close this issue since it is no longer could be reproduced.
Vadim

**Closed by vgrem** 2019-10-21 22:56 UTC
Labels: bug
