### ISSUE TITLE
Unable to create a folder on on-premise SP 2013

### ISSUE THREAD

**Issue by milled00** [vgrem/phpSPO#79] opened 2017-07-21 15:54 UTC
Hi,

I'm trying to create a folder on an on-prem 2013 site using the following code:

<?php

use Office365\PHP\Client\Runtime\Auth\NetworkCredentialContext;
use Office365\PHP\Client\SharePoint\ClientContext;

require_once 'E:\php\phpSPO-master\vendor\autoload.php';

//global $Settings;

try {

	$authCtx = new NetworkCredentialContext($Username, $Password);
	$authCtx->AuthType = CURLAUTH_NTLM; //NTML Auth schema
	$ctx = new ClientContext($Url, $authCtx);

	$folderName = '99999';
	$parentFolderUrl = '/Site/DocLib';
	$parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl($parentFolderUrl);
	$childFolder = $parentFolder->getFolders()->add($folderName);
	$ctx->executeQuery();

}
catch (Exception $e) {
	echo $e->getMessage(), '<pre>';
	var_dump($e->getTrace());
	echo '</pre>';
}

?>

Unfortunately the following warnings are produced from the executeQuery method:

Warning: First parameter must either be an object or the name of an existing class in E:\php\phpSPO-master\src\Runtime\OData\ODataPayloadSerializer.php on line 52

Warning: First parameter must either be an object or the name of an existing class in E:\php\phpSPO-master\src\Runtime\OData\ODataPayloadSerializer.php on line 55

Notice: Trying to get property of non-object in E:\php\phpSPO-master\src\Runtime\OData\ODataPayloadSerializer.php on line 72

Warning: Invalid argument supplied for foreach() in E:\php\phpSPO-master\src\Runtime\ClientValueObject.php on line 39

Warning: First parameter must either be an object or the name of an existing class in E:\php\phpSPO-master\src\Runtime\OData\ODataPayloadSerializer.php on line 52

Warning: First parameter must either be an object or the name of an existing class in E:\php\phpSPO-master\src\Runtime\OData\ODataPayloadSerializer.php on line 55

Warning: Invalid argument supplied for foreach() in E:\php\phpSPO-master\src\Runtime\ClientObject.php on line 139

Any ideas?

Thanks and regards,
Dave Miller

**Comment by milled00** [comment] 2017-07-21 15:55
Sorry - the code has been messed up:

`<?php

use Office365\PHP\Client\Runtime\Auth\NetworkCredentialContext;
use Office365\PHP\Client\SharePoint\ClientContext;

require_once 'E:\php\phpSPO-master\vendor\autoload.php';

//global $Settings;

try {

	$authCtx = new NetworkCredentialContext($Username, $Password);
	$authCtx->AuthType = CURLAUTH_NTLM; //NTML Auth schema
	$ctx = new ClientContext($Url, $authCtx);

	$folderName = '99999';
	$parentFolderUrl = '/Site/DocLib';
	$parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl($parentFolderUrl);
	$childFolder = $parentFolder->getFolders()->add($folderName);
	$ctx->executeQuery();

}
catch (Exception $e) {
	echo $e->getMessage(), '<pre>';
	var_dump($e->getTrace());
	echo '</pre>';
}

?>`

**Comment by vgrem** [comment] 2018-04-19 07:00
I propose to close the issue since it could no longer be reproduced.

**Closed by vgrem** 2018-04-19 07:00 UTC
Labels: question, sharepoint-onprem, documentation
