### ISSUE TITLE
Authentication failed: The specified member name is either invalid or empty.

### ISSUE THREAD

**Issue by marcfath** [vgrem/phpSPO#13] opened 2016-04-04 19:59 UTC
Regardless of what I put in the userid and password parameters (valid or not) I get the same return from acquireTokenForUser call.  I have tried valid userids (which I can log in to Sharepoint with) and dummy userids I expect to fail....same result.

**Comment by robertblock** [comment] 2016-04-26 19:21
I'm having the same issue, though I don't know a lot about Sharepoint. Yet.

**Comment by ctcudd** [comment] 2016-05-31 23:49
What kind of Sharepoint instance are you connecting to?

If you are connecting to a local Sharepoint instance, aka "Sharepoint Intranet", please try the [NtlmConnectExample](https://github.com/vgrem/phpSPO/blob/master/examples/NtlmConnectExample.php)

**Comment by vgrem** [comment] 2016-11-04 09:15
I propose to close this issue since could not reproduce this issue

To summarize, in case of SharePoint authentication:

1. [NetworkCredentialContext class](https://github.com/vgrem/phpSPO/blob/master/src/Runtime/Auth/NetworkCredentialContext.php) - support basic, digest, NTLM, and Kerberos authentication schemes(SharePoint On-Premise)

2. [AuthenticationContext class](https://github.com/vgrem/phpSPO/blob/master/src/Runtime/Auth/AuthenticationContext.php) / used for SharePoint Online & Office 365 authentication

**Closed by vgrem** 2016-11-04 09:15 UTC

**Comment by mpastas** [comment] 2018-06-22 21:46
I'm getting exactly the same message trying to connect to Sharepoint Online:

**The specified member name is either invalid or empty.**
    ```
    $username = "john.doe"; //Not using the @domain.com
    $password = "password"
    $authCtx = new AuthenticationContext($url);
    $authCtx->acquireTokenForUser($username, $password);
    $ctx = new ClientContext($url, $authCtx);
```

**Comment by Sofiaaccount** [comment] 2018-08-07 17:10
Same issue here, with correct login pass i get  Authentication failed: Warning: DOMXPath::query(): Undefined namespace prefix

how can i resolve this ?
Thanks

**Comment by Eiglimar** [comment] 2019-05-30 19:38
hello guys anyone solved this?
